version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: hotel
      MYSQL_ROOT_PASSWORD: Nizam@143
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: hotel-management-system
    container_name: hotel-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hotel
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nizam@143
#      JWT_SECRET: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
#      JWT_EXPIRATION: 1800000
    depends_on:
      - db

volumes:
  mysql-data:
